name: Calling workflow test-vinod_pal

on:    
 schedule:
   - cron : '15 11 * * *'
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
     Branches: Test-123
    secrets: inherit
    permissions:
     id-token: write
     contents: write

