name: Calling workflow test-vinod_pal

on:    
 #schedule:
   #- cron : '28 09 * * *'
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
     id-token: write
     contents: write

