name: Calling workflow test-vinod_pal

on:
 schedule:
  - cron : '49 13 * * *'
 
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit
    permissions:
     id-token: write
     contents: write

