name: Call a reusable workflow

on:
 workflow_dispatch:
  inputs:
      environment:
        type: environment
 #schedule:
 # - cron : '15 9 * * *'
        
jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

