name: Calling workflow test-vinod_pal

on:
 schedule:
   - cron : '05 14 * * *'
 
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
       environment: dev
       type: string
    secrets: inherit
    permissions:
     id-token: write
     contents: write

