name: Calling workflow test-vinod_pal

on:
 workflow_dispatch:
   inputs:
      environment:
        type: environment
 schedule:
   - cron : '0 13 * * *'
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      Branch: Test-123
    secrets: inherit
    permissions:
     id-token: write
     contents: write

