name: Calling workflow test-vinod_pal

on:
 workflow_dispatch:
  inputs:
      environment:
        type: environment
  
 schedule:
   - cron : '55 9 * * *'
 

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
     environment: dev
    secrets: inherit
    permissions:
     id-token: write
     contents: write

