name: Calling workflow test-vinod_pal

on:
  schedule:
    - cron : '20 14 * * *'

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      use_env_as_build_ref: true
    secrets: inherit
    permissions:
      id-token: write
      contents: write

